---
services:
  back:
    image: secunda-backend
    container_name: secunda-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./log:/app/log
      - ./logs:/app/logs
      - ./stat:/app/stat
    depends_on:
      - secunda-db
    networks:
      - secunda-net

  secunda-db:
    image: postgres:17.4
    container_name: secunda-pgsql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: secunda  # база создаётся автоматически
    env_file:
      - .env  # Загружаем переменные из .env
    # ports:
    #   - 5432:5432
    volumes:
      - ./pgcheck:/var/lib/postgresql/data
      - /log:/log
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s    # как часто проверять
      timeout: 5s      # максимальное время ожидания ответа
      retries: 5       # сколько раз подряд должно быть ОК
      start_period: 30s # сколько времени дать на начальную загрузку
    networks:
      - secunda-net

networks:
  secunda-net:
    name: secunda-net
    external: true
