"""create tables

Revision ID: 065d0ff6387b
Revises: 
Create Date: 2025-08-07 03:01:14.725670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065d0ff6387b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('name', sa.Text(), nullable=False, comment='Название деятельности'),
    sa.Column('parent_id', sa.Uuid(), nullable=True, comment='Родительская деятельность'),
    sa.Column('level', sa.Integer(), nullable=False, comment='Уровень вложенности (1-3)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building',
    sa.Column('address', sa.Text(), nullable=False, comment='Адрес здания'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='Широта'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='Долгота'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('name', sa.Text(), nullable=False, comment='Название организации'),
    sa.Column('building_id', sa.Uuid(), nullable=False, comment='Здание'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_activity',
    sa.Column('organization_id', sa.Uuid(), nullable=False, comment='Организация'),
    sa.Column('activity_id', sa.Uuid(), nullable=False, comment='Деятельность'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_phone',
    sa.Column('organization_id', sa.Uuid(), nullable=False, comment='Организация'),
    sa.Column('phone_number', sa.Text(), nullable=False, comment='Номер телефона'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_phone')
    op.drop_table('organization_activity')
    op.drop_table('organization')
    op.drop_table('building')
    op.drop_table('activity')
    # ### end Alembic commands ###
